// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/urfave/cli/v2"
	"github.com/wow-yorick/tools/blog-template/cmd"
)

// Injectors from wire.go:

func Initialize() cli.Commands {
	templateCmd := cmd.NewTemplateCmd()
	publishCmd := cmd.NewPublishCmd()
	cmdHandler := CmdHandler{
		TpCmd:  templateCmd,
		pshCmd: publishCmd,
	}
	commands := NewCmds(cmdHandler)
	return commands
}

// wire.go:

var providerSet = wire.NewSet(
	NewCmds, cmd.NewTemplateCmd, cmd.NewPublishCmd, wire.Struct(new(CmdHandler), "*"),
)
